const initialState = {
  state: {
    pendingCount: [],
    fcaf_status: "",
    fcaf_fileName: "Pending",
    fcaf_note: " ",
    cdf_status: "pending",
    cdf_fileName: "fileName",
    cdf_note: " ",
    bi_status: "pending",
    bi_fileName: "fileName",
    bi_note: " ",
    ota_status: "pending",
    ota_fileName: "fileName",
    ota_note: " ",
    aps_status: "pending",
    aps_fileName: "fileName",
    aps_note: " ",
    hwua_status: "pending",
    hwua_fileName: "fileName",
    hwua_note: " ",
    wc_status: "pending",
    wc_fileName: "fileName",
    wc_note: " ",
    wuod_status: "pending",
    wuod_fileName: "fileName",
    wuod_note: " ",
    owsc_status: "pending",
    owsc_fileName: "fileName",
    owsc_note: " ",
    bp_status: "pending",
    bp_fileName: "fileName",
    bp_note: " ",
    ldp_status: "pending",
    ldp_fileName: "fileName",
    ldp_note: " ",
    ldpa_status: "pending",
    ldpa_fileName: "fileName",
    ldpa_note: " ",
    pad_status: "pending",
    pad_fileName: "fileName",
    pad_note: " ",
    sdp_tatus: "pending",
    sdp_fileName: "fileName",
    sdp_note: " ",
    sdpa_status: "pending",
    sdpa_fileName: "fileName",
    sdpa_note: " ",
    tdp_status: "pending",
    tdp_fileName: "fileName",
    tdp_note: " ",
    tdpa_status: "pending",
    tdpa_fileName: "fileName",
    tdpa_note: " ",
    fdp_status: "pending",
    fdp_fileName: "fileName",
    fdp_note: " ",
    fdpa_status: "pending",
    fdpa_fileName: "fileName",
    fdpa_note: " ",
    coi_status: "pending",
    coi_fileName: "fileName",
    coi_note: " ",
    moa_status: "pending",
    moa_fileName: "fileName",
    moa_note: " ",
    aoa_status: "pending",
    aoa_fileName: "fileName",
    aoa_note: " ",
    sr_status: "pending",
    sr_fileName: "fileName",
    sr_note: " ",
    scs_status: "pending",
    scs_fileName: "fileName",
    scs_note: " ",
    ccre_status: "pending",
    ccre_fileName: "fileName",
    ccre_note: " ",
    cbs_status: "pending",
    cbs_fileName: "fileName",
    cbs_note: " ",
    pbs_status: "pending",
    pbs_fileName: "fileName",
    pbs_note: " ",
    pow_status: "pending",
    pow_fileName: "fileName",
    pow_note: " ",
    cap_status: "pending",
    cap_fileName: "fileName",
    cap_note: " ",
    gofl_status: "pending",
    gofl_fileName: "fileName",
    gofl_note: " ",
    cora_status: "pending",
    cora_fileName: "fileName",
    cora_note: " ",
    fodsa_status: "pending",
    fodsa_fileName: "fileName",
    fodsa_note: " ",
    status: "pending",
    fcr_fileName: "fileName",
    fcr_note: " ",
    shs_status: "pending",
    shs_fileName: "fileName",
    shs_note: " ",
    df_status: "pending",
    df_fileName: "fileName",
    df_note: " ",
    spare: "",
    spare1: "",
    spare2: "",
    spare3: "",
    spare4: "",
    spare5: "",
    spare_Text: "",
    spare1_Text: "",
    spare2_Text: "",
    spare3_Text: "",
    spare4_Text: "",
    spare5_Text: "",
    spare_fileName: "",
    spare1_fileName: "",
    spare2_fileName: "",
    spare3_fileName: "",
    spare4_fileName: "",
    spare5_fileName: "",
  },
};
export const clReducer = (state = initialState, action) => {
  switch (action.type) {
    case "CREATE_CL":
      return {
        ...state,
        state: action.payload,
      };
    case "GET_CL":
      return {
        ...state,
        state: action.payload,
      };
      break;

    default:
      return state;
      break;
  }
};
