const initialState = {
  state: {
    pendingCount: [],
    fcaf_status: "pending",
    fcaf_fileName: "fileName",
    fcaf_note: " ",
    cdf_status: "pending",
    cdf_fileName: "fileName",
    cdf_note: " ",
    bi_status: "pending",
    bi_fileName: "fileName",
    bi_note: " ",
    ota_status: "pending",
    ota_fileName: "fileName",
    ota_note: " ",
    aps_status: "pending",
    aps_fileName: "fileName",
    aps_note: " ",
    hwua_status: "pending",
    hwua_fileName: "fileName",
    hwua_note: " ",
    wc_status: "pending",
    wc_fileName: "fileName",
    wc_note: " ",
    wuod_status: "pending",
    wuod_fileName: "fileName",
    wuod_note: " ",
    owsc_status: "pending",
    owsc_fileName: "fileName",
    owsc_note: " ",
    bp_status: "pending",
    bp_fileName: "fileName",
    bp_note: " ",
    ldp_status: "pending",
    ldp_fileName: "fileName",
    ldp_note: " ",
    ldpa_status: "pending",
    ldpa_fileName: "fileName",
    ldpa_note: " ",
    pad_status: "pending",
    pad_fileName: "fileName",
    pad_note: " ",
    sdp_status: "pending",
    sdp_fileName: "fileName",
    sdp_note: " ",
    sdpa_status: "pending",
    sdpa_fileName: "fileName",
    sdpa_note: " ",
    tdp_status: "pending",
    tdp_fileName: "fileName",
    tdp_note: " ",
    tdpa_status: "pending",
    tdpa_fileName: "fileName",
    tdpa_note: " ",
    fdp_status: "pending",
    fdp_fileName: "fileName",
    fdp_note: " ",
    fdpa_status: "pending",
    fdpa_fileName: "fileName",
    fdpa_note: " ",
    coi_status: "pending",
    coi_fileName: "fileName",
    coi_note: " ",
    moa_status: "pending",
    moa_fileName: "fileName",
    moa_note: " ",
    aoa_status: "pending",
    aoa_fileName: "fileName",
    aoa_note: " ",
    sr_status: "pending",
    sr_fileName: "fileName",
    sr_note: " ",
    scs_status: "pending",
    scs_fileName: "fileName",
    scs_note: " ",
    ccre_status: "pending",
    ccre_fileName: "fileName",
    ccre_note: " ",
    cbs_status: "pending",
    cbs_fileName: "fileName",
    cbs_note: " ",
    pbs_status: "pending",
    pbs_fileName: "fileName",
    pbs_note: " ",
    pow_status: "pending",
    pow_fileName: "fileName",
    pow_note: " ",
    cap_status: "pending",
    cap_fileName: "fileName",
    cap_note: " ",
    gofl_status: "pending",
    gofl_fileName: "fileName",
    gofl_note: " ",
    cora_status: "pending",
    cora_fileName: "fileName",
    cora_note: " ",
    fodsa_status: "pending",
    fodsa_fileName: "fileName",
    fodsa_note: " ",
    status: "pending",
    fcr_fileName: "fileName",
    fcr_note: " ",
    shs_status: "pending",
    shs_fileName: "fileName",
    shs_note: " ",
    df_status: "pending",
    df_fileName: "fileName",
    df_note: " ",
    clg_status:"",
    clg_fileName:"fileName",
    TIC1:false,
    TIC2:false,
    TIC3:false,
    TIC4:false,
    TIC5:false,
    TIC6:false,
    TIC7:false,
    TIC8:false,
    TIC9:false,
    TIC21:false,
    TIC22:false,
    TIC23:false,
    TIC24:false,
    TIC25:false,
    TIC26:false,
    TIC27:false,
    TIC28:false,
    TIC29:false,
  
   KYCC1:false,
   KYCC2:false,
   KYCC3:false,
   KYCC4:false,
   KYCC5:false,
   KYCC6:false,
   KYCC7:false,
   KYCC8:false,
   KYCC9:false,
   KYCC10:false,
   KYCC21:false,
   KYCC22:false,
   KYCC23:false,
   KYCC24:false,
   KYCC25:false,
   KYCC26:false,
   KYCC27:false,
   KYCC28:false,
   KYCC29:false,
 
   KYBC1:false,
   KYBC2:false,
   KYBC3:false,
   KYBC4:false,
   KYBC5:false,
   KYBC6:false,
   KYBC7:false,
   KYBC8:false,
   KYBC9:false,
   KYBC10:false,
   KYBC21:false,
   KYBC22:false,
   KYBC23:false,
   KYBC24:false,
   KYBC25:false,
   KYBC26:false,
   KYBC27:false,
   KYBC28:false,
   KYBC29:false,

   SDC1:false,
   SDC2:false,
   SDC3:false,
   SDC4:false,
   SDC5:false,
   SDC6:false,
   SDC7:false,
   SDC8:false,
   SDC9:false,
   SDC10:false,
   SDC21:false,
   SDC22:false,
   SDC23:false,
   SDC24:false,
   SDC25:false,
   SDC26:false,
   SDC27:false,
   SDC28:false,
   SDC29:false,
   ti:false,
   kyc:false,
   kyb:false,
   sd:false,
   md:false,
   ti_status:"pending",
   kyc_status:"pending",
   kyb_status:"pending",
   kyb_status:"pending",
   checkby:"",
   senttosolby:"",
   sentDate:"",
  notes:[{
    date:"",
    text:""
  }]
     
  },
};
export const clReducer = (state = initialState, action) => {
  switch (action.type) {
    case "CREATE_CL":
      return {
        ...state,
        state: action.payload,
      };
    case "GET_CL":
      return {
        ...state,
        state: action.payload,
      };
      break;

    default:
      return state;
      break;
  }
};
